### ISSUE TITLE
Cannot extract the publication date for some pages

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#10]
When loading this page (http://www.bbc.com/sport/olympics/37063284) in annotation mode, the console shows the following error message

extensions::uncaught_exception_handler:8 
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'innerText' of undefined
    at getArticleTitleAndPublicationDate (chrome-extension://hbellpimdlanffbgemakfohcbaepogoh/annotate.js:614:38)
    at beginAnnotation (chrome-extension://hbellpimdlanffbgemakfohcbaepogoh/annotate.js:736:5)
    at chrome-extension://hbellpimdlanffbgemakfohcbaepogoh/annotate.js:723:10

**Comment by idmswz** [comment]
Added an additional case for bbc sport to retrieve publish date.

**Comment by kite1988** [comment]
It seems the publication date is still incorrect.  Here is the parameter that backend received for annotation creation.

  Parameters: {"annotation"=>{"ann_id"=>"45480971", "user_id"=>"375", "selected_text"=>"stage", "translation"=>"舞台", "lang"=>"zh_CN", "url"=>"http://www.bbc.com/sport/olympics/37063284", "url_postfix"=>"sport/olympics/37063284", "website"=>"bbc", "paragraph_idx"=>"5", "text_idx"=>"0", "title"=>"Rio Olympics 2016: 'Not what the Olympics are about' - judo player refuses to shake hands - BBC Sport", "**publication_date"=>"1970-1-18"}**}

**Comment by idmswz** [comment]
Fixed it with multiplying the timestamp by 1000 and offseting it to the right timezone.
