### ISSUE TITLE
A new API for translation and quiz generation

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#13]
This issue is depended on https://github.com/kite1988/wordnews_chrome_extension/issues/15

In learning mode, a new API "show_learn_words" has been created to replace "show/show_by_dictionary/http://imsforwordnews.herokuapp.com/show" and "getQuiz.json" APIs.

The new API takes the whole article (i.e., all paragraphs) as parameter, and returns the words to be learned with their translation (both machine translation and annotations when exist) and quiz at the article level.   Please refer to the API doc for details.

Please revise the html and javascript code accordingly.

**Comment by kite1988** [comment]
Before sending the article to API "show_learn_words", please pre-process paragraph's text by:
1. Replace all non-ascii token (e.g., word, character) by a whitespace
2. Replace \n by a whitespace

**Comment by idmswz** [comment]
Changed learn.js to use the new API and refractor code. Need to do testing.

**Comment by kite1988** [comment]
When send the article in the one-paragraph mode (one paragraph per request), please 
1.  exclude extreme short paragraph (e.g., less than 10 words) and 
2.  shuffle the order of paragraphs so that users do not always learn words in top paragraph.

In the all-paragraph mode (i.e., send all paragraphs of the article per request), the backend will handle 2 automatically but not 1.

**Comment by kite1988** [comment]
Note the API has been updated: the urls of Chinese word pronunciation audio have been returned. 

For the UI, javascript should allow multiple audio to be played in a row. http://stackoverflow.com/questions/15672370/playing-an-array-of-sound-files
http://stackoverflow.com/questions/16916896/playing-two-files-in-a-row-in-javascript

**Comment by idmswz** [comment]
Increased the number of words to 10 as a condition before sending to server.
Implemented a simple audio queue system for pronunciation.

**Comment by kite1988** [comment]
A new field "weighted_vote" (i.e.,  weighted score of explicit and implicit vote) is returned from API.  This value should be used to sort machine translation and human annotations.

**Comment by kite1988** [comment]
A new field "more_url"  is returned from the API for translations and the word to test.
