### ISSUE TITLE
Replace translationUrl by translation engine name

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#15]
For the updated API, the translationUrl is no longer needed. Instead, the name of translator will be passed to server.  The three names are:
- dict (dictionary-based translation)  
- bing (MS bing translator)
- ims (HongJin's translator)

Please revise relevant javascript files (e.g., popup.js, learn.js).

**Comment by idmswz** [comment]
Fixed this issue together with changes in learn.js API.
