### ISSUE TITLE
Annotation Language is missing

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#16]
Started GET "/show_user_annotation_history?user_id=460&**lang=**" for 137.132.200.109 at 2016-08-23 06:29:44 +0000
Processing by AnnotationsController#show_user_annotation_history as JSON
  Parameters: {"user_id"=>"460", **"lang"=>""**}

**Comment by idmswz** [comment]
Correct the variable name for annotation language as annotationLanguage does not exists anymore.
