### ISSUE TITLE
Log user's activity

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#30]
To better understand user's activities, the client side should collect user's detailed behaviorists of using our application, and send to server via '/log' endpoint.

The parameters are:

```
{
  "user_id": 
  "activity": // use the API name for most actions
  "time_elapsed": // in ms
  "detail": {} // optional for some actions
}
```

The following actions and information are valuable to collect:

**1. take_quiz** (view the popup and then select the choice)
-  the total time used to finish a quiz (from clicking underline word to choose a answer) 
- the mouse hovering patterns (i.e., move mouse from one choice to another), and the time of focusing on the choice, e.g.,

Below is an example log.

```

{
    "user_id": 111,
    "activity": "take_quiz",
    "time_elapsed": 5000,  // in ms,
    "detail": {
        "choices": ["word_1", "word_2", "word_3", "word_4"],  // according to the layout of choices, from top left to  bottom right.
        "answer": 2,  // the index of user's answer in choices
        "ground_truth": 3, // the index of correct answer in choices
        "patterns": [
                    {"hover": [0, 1000]}, 
                    {"hover": [3, 2000]}, 
                    {"no_focus": 5000}, 
                    {"hover": [2, 3000]},
                    {"click": 2} 
                ]
    }
}

```

Note: 
If the user takes more than 1 minute for a quiz,  we will discard such log since it is likely that the user is doing something else.

**2. quit_quiz** (view the popup and then close it without submitting any answer)
Similar to take_quiz, but change the name of action to be "quit_quiz"

**3. view**
The action name is "view", and "detail" field is committed.

**Comment by idmswz** [comment]
take_quiz and quit_quiz will be stored as take_quiz. The only differences between these two is the patterns. For quit_quiz, it will end with "close" whereas take_quiz will end with "Click on index: word".
