### ISSUE TITLE
Learning mode: allow users to input their own translation

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#32]
In the learning mode, if the user is unsatisfied with all the provided translation, she can input her own translation, which is similar to annotation except the user cannot select the word to be annotated.

Please call '/create_annotation'  to send the annotation to server. Note:
- "ann_id" could be generated similarly to the one in annotation mode
- "lang" is the current learning language
- The position of the word is available in the response of "/show_learn_words", where "word_index" is the "text_idx", and "paragraph_index" is the "paragraph_idx".

**Comment by idmswz** [comment]
When user clicked "No", it will hide the "Yes" and "No" buttons and be replaced with textbox and "Submit" button.

![image](https://cloud.githubusercontent.com/assets/20508653/19107160/87daf896-8b1d-11e6-8ac5-795c58689113.png)
