### ISSUE TITLE
Annotation Id is out of integer range 

### ISSUE THREAD

**Issue by kite1988** [kite1988/wordnews_chrome_extension#4]
The annotation id (ann_id) is stored as signed integer (-2147483648 to +2147483647) in database, while such IDs generated by client side (https://github.com/kite1988/wordnews_chrome_extension/blob/master/annotate.js#L550
) exceed the integer range sometimes.

PG::NumericValueOutOfRange: ERROR:  value "2803632470" is out of range for type integer

@idmswz: can you take a look at this issue?  Thanks!

**Comment by idmswz** [comment]
For generation of annotation panel ID, I have shorten the number of bits to 7 instead of 8 to prevent out of range.
